version: '3'
        services:
                dbos:
                  images: mysql:5.7
                  volumes:
                          - mysql_storage_new:/var/lib/mysql
                  restart: always
                  environment:
                          MYSQL_ROOT_PASSWORD: urrootpass
                          MYSQL_USER: ur_name
                          MYSQL_PASSWORD: urpass
                          MYSQL_DATABASE: mydb
                
                Wordpress:
                  images: wordpress:5.1.1-php7.3-apache
                  restart: always
                  depends_on:
                          - dbos
                  ports:
                          - 8080:80
                          - 1234:81
                  environment:
                          WORDPRESS_DB_HOST: dbos
                          WORDPRESS_DB_USER: ur_name
                          WORDPRESS_DB_PASSWORD: urpass
                          WORDPRESS_DB_NAME: mydb
                  volumes: 
                         - mysql_storage_new:/var/www/html
volumes:
  wp_storage_new:
  mysql_storage_new:
